apiVersion: v1
kind: Pod
metadata:
  name: ns-pod
  labels:
    app: demoapp
  namespace: prod
spec:
  containers:
    - name: my-containers
      image: nginx:1.29
      ports:
        - containerPort: 80
  